# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\desktop2\2021\scripts\python\PyCharmProjects\awake\KeepScreenAwake\awake.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KeepScreenAwakeUtility(object):
    def setupUi(self, KeepScreenAwakeUtility):
        KeepScreenAwakeUtility.setObjectName("KeepScreenAwakeUtility")
        KeepScreenAwakeUtility.resize(512, 362)
        self.centralwidget = QtWidgets.QWidget(KeepScreenAwakeUtility)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nothing = QtWidgets.QFrame(self.centralwidget)
        self.nothing.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.nothing.setStyleSheet("QPushButton {\n"
"border: none;\n"
"padding: 5px 10px;\n"
"background-color: #f7f7f7;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QFrame {\n"
"border-top-right-radius: 5px;\n"
"border-top-left-radius: 5px;\n"
"    background-color: rgb(83, 83, 83);\n"
"}")
        self.nothing.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nothing.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nothing.setObjectName("nothing")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.nothing)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dragFrame = QtWidgets.QFrame(self.nothing)
        self.dragFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dragFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dragFrame.setObjectName("dragFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dragFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.dragFrame)
        self.label.setStyleSheet("image: url(:/newPrefix/images/24x24/cil-cursor.png);\n"
"color: gray;\n"
"font-weight:bold;\n"
"padding: 4px;\n"
"min-width: 20px;\n"
"margin-left:5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.dragFrame)
        self.label_3.setStyleSheet("font-weight:bold;\n"
"color: lightgray;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.dragFrame)
        self.minimize = QtWidgets.QPushButton(self.nothing)
        self.minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize.setStyleSheet("\n"
"QPushButton {\n"
"image: url(:/newPrefix/images/24x24/cil-window-minimize.png);\n"
"\n"
"background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #666666;\n"
"}")
        self.minimize.setText("")
        self.minimize.setObjectName("minimize")
        self.horizontalLayout.addWidget(self.minimize)
        self.close = QtWidgets.QPushButton(self.nothing)
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setStyleSheet("\n"
"QPushButton {\n"
"    image: url(:/newPrefix/images/20x20/cil-x.png);\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: tomato;\n"
"}")
        self.close.setText("")
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addWidget(self.nothing)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("border-bottom-right-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"background-color: rgb(102, 102, 102);\n"
"font-size:16px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("color: #fff;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.AutoClicker = QtWidgets.QWidget()
        self.AutoClicker.setObjectName("AutoClicker")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.AutoClicker)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.AutoClicker)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.frame_6)
        self.frame_13.setStyleSheet("QFrame {\n"
"background-color: #727272;\n"
"color: #fff;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_23 = QtWidgets.QFrame(self.frame_13)
        self.frame_23.setStyleSheet("QFrame {\n"
"background-color: #727272;\n"
"color: #fff;\n"
"}\n"
"QRadioButton {\n"
"background-color: none;\n"
"}\n"
"")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_7.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_22 = QtWidgets.QFrame(self.frame_23)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.frame_22)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.frame_5)
        self.textEdit.setEnabled(True)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        # font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        font = QtGui.QFont()
        # font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("border-radius: 3px;")
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMinimum(1)
        self.spinBox.setProperty("value", 5)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.frame_34 = QtWidgets.QFrame(self.frame_22)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.stopBtn = QtWidgets.QPushButton(self.frame_34)
        self.stopBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopBtn.setStyleSheet("QPushButton {\n"
"    image: url(:/newPrefix/images/24x24/cil-media-stop.png);\n"
"background-color:#ff6f6f;\n"
"padding:5px;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#ff4c4c;\n"
"}")
        self.stopBtn.setText("")
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_12.addWidget(self.stopBtn)
        self.startBtn = QtWidgets.QPushButton(self.frame_34)
        self.startBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startBtn.setStyleSheet("QPushButton {\n"
"image: url(:/newPrefix/images/24x24/cil-media-play.png);\n"
"background-color: #84c184;\n"
"padding: 5px;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #66b266;\n"
"}")
        self.startBtn.setText("")
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_12.addWidget(self.startBtn)
        self.verticalLayout_8.addWidget(self.frame_34)
        self.horizontalLayout_7.addWidget(self.frame_22)
        self.frame_19 = QtWidgets.QFrame(self.frame_23)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_40 = QtWidgets.QFrame(self.frame_19)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.frame_40)
        self.label_6.setStyleSheet("color: lightgray;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.mouseLastUpdate = QtWidgets.QLabel(self.frame_40)
        self.mouseLastUpdate.setStyleSheet("font-size: 10px;\n"
"color: lightgray;")
        self.mouseLastUpdate.setObjectName("mouseLastUpdate")
        self.horizontalLayout_10.addWidget(self.mouseLastUpdate, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_15.addWidget(self.frame_40)
        self.mouseList = QtWidgets.QListWidget(self.frame_19)
        font = QtGui.QFont()
        # font.setPointSize(-1)
        self.mouseList.setFont(font)
        self.mouseList.setStyleSheet("background-color: rgba(148, 148, 148, 102);\n"
"border-radius:3px;\n"
"padding:5px;\n"
"font-size: 14px;")
        self.mouseList.setObjectName("mouseList")
        self.verticalLayout_15.addWidget(self.mouseList)
        self.progressBar = QtWidgets.QProgressBar(self.frame_19)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setStatusTip("")
        self.progressBar.setStyleSheet("QProgressBar{\n"
"font-size: 1px;\n"
"color: rgba(0,0,0,0.1);\n"
"min-height: 4px;\n"
"max-height: 4px;\n"
"\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_15.addWidget(self.progressBar)
        self.verticalLayout_15.setStretch(1, 1)
        self.horizontalLayout_7.addWidget(self.frame_19)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_11.addWidget(self.frame_23)
        self.horizontalLayout_6.addWidget(self.frame_13)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.AutoClicker)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mouseTime = QtWidgets.QLabel(self.frame_4)
        self.mouseTime.setStyleSheet("color: lightgray;\n"
"font-size: 10px;")
        self.mouseTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mouseTime.setObjectName("mouseTime")
        self.horizontalLayout_3.addWidget(self.mouseTime)
        self.information = QtWidgets.QLabel(self.frame_4)
        self.information.setStyleSheet("color: lightgray;\n"
"font-size: 10px;")
        self.information.setText("")
        self.information.setAlignment(QtCore.Qt.AlignCenter)
        self.information.setObjectName("information")
        self.horizontalLayout_3.addWidget(self.information)
        self.mousexy = QtWidgets.QLabel(self.frame_4)
        self.mousexy.setStyleSheet("color: lightgray;\n"
"font-size: 10px;")
        self.mousexy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mousexy.setObjectName("mousexy")
        self.horizontalLayout_3.addWidget(self.mousexy)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_11 = QtWidgets.QFrame(self.frame_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addWidget(self.frame_11)
        self.verticalLayout.addWidget(self.frame_2)
        KeepScreenAwakeUtility.setCentralWidget(self.centralwidget)

        self.retranslateUi(KeepScreenAwakeUtility)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(KeepScreenAwakeUtility)

    def retranslateUi(self, KeepScreenAwakeUtility):
        _translate = QtCore.QCoreApplication.translate
        KeepScreenAwakeUtility.setWindowTitle(_translate("KeepScreenAwakeUtility", "MainWindow"))
        self.label_3.setText(_translate("KeepScreenAwakeUtility", "Keep Screen Awake"))
        self.textEdit.setHtml(_translate("KeepScreenAwakeUtility", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; color:#ffffff;\">Use the spin box below to choose the amount of minutes between each mouse movement. </span><span style=\" font-size:16px; font-style:italic; color:#ffffff;\">Typically your screen will turn off in 5 - 15 minutes without activity.</span><span style=\" font-size:16px; color:#ffffff;\"> Then click the green button to begin. and the red button to stop.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; color:#ffffff;\">Made With </span><img src=\":/newPrefix/images/20x20/cil-heart.png\" /><span style=\" font-size:16px; color:#ffffff;\"> By Gabe</span></p></body></html>"))
        self.label_2.setText(_translate("KeepScreenAwakeUtility", "Minutes: "))
        self.stopBtn.setToolTip(_translate("KeepScreenAwakeUtility", "Stop Auto Clicker!"))
        self.startBtn.setToolTip(_translate("KeepScreenAwakeUtility", "Start Auto Clicker!"))
        self.label_6.setText(_translate("KeepScreenAwakeUtility", "Event Log"))
        self.mouseLastUpdate.setText(_translate("KeepScreenAwakeUtility", "            00:00:00 am"))
        self.mouseTime.setText(_translate("KeepScreenAwakeUtility", "00:00:00 am"))
        self.mousexy.setText(_translate("KeepScreenAwakeUtility", "(x,y)"))
import resources_rc
